
url = "https://vkfswyvnywxrmxrmrfqm.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZnN3eXZueXd4cm14cm1yZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MzEyNTEsImV4cCI6MjA3NzIwNzI1MX0.cJANFlrZzgGRoWJoE5QVJsKce2_adSR7Ji-XTrtwvsQ"